### ISSUE TITLE
Timeline / Showdown / Hunt Menues not working with TTS 13

### ISSUE THREAD

**Issue by thargan81** [jordanmchavez/kdm-tts#3]
This has already been mentioned on the Workshop page, but there's no indication how active you are there.
The recent update to TTS has caused issues with the Hunt and Showdown menus, where you pick a quarry, and the time line panel. When the relevant button is pressed, the panel opens as you'd expect, but there's no content inside the areas with a scroll bar.

**Comment by jordanmchavez** [comment]
Fixed in 0.33.
