### ISSUE TITLE
Export fails if there are gear stacks

### ISSUE THREAD

**Issue by Voidheartd** [jordanmchavez/kdm-tts#4]
Noticed an issue with exporting. It won't export if there is a stack of items in the settlement gear storage. I keep all items of the same type like founding stones in stacks. I can't just unstack because there is currently more gear than spaces.

**Comment by jordanmchavez** [comment]
Thanks for the bug report. This is a known issue and I intentionally limited gear exports to single cards (not stacks) for simplicity. I want to remove this restriction in the next major update.

In the meantime, a workaround is to put all of your gear/resources/etc that won't fit on the board into a bag, and copy and paste that bag into the new save.
