### ISSUE TITLE
Bug Report:

### ISSUE THREAD

**Issue by Seranuelian** [jordanmchavez/kdm-tts#5]
Hey, 

I was wondering if there was a platform where I could report some issues I ran into to you and didnt wanna bother you on Discord.

The "Vespertine Foil" and "Hollowpoint Arrow" don't show up in the Combat UI when put into the gear grid.

**Comment by jordanmchavez** [comment]
Thanks for the bug report. I'll add these to the backlog and include them in the next update.

**Comment by jordanmchavez** [comment]
Fixed in 1.0. Looks like hollowpoint was always working, but foil wasn't.
