### ISSUE TITLE
Zanbato not showing up on Battle UI

### ISSUE THREAD

**Issue by brozmical** [jordanmchavez/kdm-tts#9]
Hey Jordan, thanks for the mod- been playing solo and really enjoyable.  Have some minor issue with the Zanbato gear card, for some reason its not showing up on the battle UI

**Comment by henriknoerr** [comment]
It's showing up for me on all 4 (Starting) survivors - not sure how that helps :)

**Comment by jordanmchavez** [comment]
I can't reproduce this: Zanbato is showing up fine in the Battle UI for me. Make sure the card's name is exactly Zanbato, no extra spaces or anything like that.
